require 'jobs/player_session_started_job'
require 'jobs/player_session_stopped_job'
require 'jobs/session_started_job'
require 'jobs/session_stopped_job'
require 'jobs/delete_server_snapshots_job'

require 'jobs/legacy_session_stopped_job'
require 'jobs/legacy_session_started_job'
require 'jobs/legacy_player_session_started_job'
require 'jobs/legacy_player_session_stopped_job'
